### PR TITLE
Change channels from alpha to candidate

### PR DESCRIPTION
**Pull request by clobrano**

### CODE REVIEW

**Review by razo7 — COMMENTED** [review]
How about updating the channel from the makefile like the other Medik8s operators (see in [FAR](https://github.com/medik8s/fence-agents-remediation/pull/8/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L29-L32)?

This way we have one (and automatic) way of setting the bundle's channel (and default channel) :)

**Comment by slintes** [comment]
> How about updating the channel from the makefile like the other Medik8s operators (see in [FAR](https://github.com/medik8s/fence-agents-remediation/pull/8/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L29-L32)?
> 
> This way we have one (and automatic) way of setting the bundle's channel (and default channel) :)

makes a lot of sense of course, but I think it's also fine to do that in a separate PR, in order to be able to move forward with adding e2e test to CI 🙂 

/test all

**Comment by slintes** [comment]
let's see if "tide" is waking up once the tests succeed... 🤔 

/lgtm
/approve

**Comment by slintes** [comment]
> let's see if "tide" is waking up

it just did 🥳

**Comment by clobrano** [comment]
> How about updating the channel from the makefile like the other Medik8s operators (see in [FAR](https://github.com/medik8s/fence-agents-remediation/pull/8/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L29-L32)?
> 
> This way we have one (and automatic) way of setting the bundle's channel (and default channel) :)

I'm sorry, I missed the message, but I like the idea :+1:

**Pull request merged**
