### PR TITLE
Add status condition to MDR CSV sample

### PR DESCRIPTION
**Pull request by clobrano**
Based on scorecard test suggestion, this change adds an example of
status condition to MDR's CSV sample.

Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>

### CODE REVIEW

**Comment by razo7** [comment]
Did it satisfy scorecard test? 
/lgtm
I am holding in case you want to merge if after a feature branch has been created.
/hold

**Comment by clobrano** [comment]
> Did it satisfy scorecard test?

yes, confirm

> I am holding in case you want to merge if after a feature branch has been created.

what do you mean? I see this as (minor) bugfix, but if you feel should not target next release I can create the release branch first and let this for the next round

**Comment by razo7** [comment]
> I see this as (minor) bugfix

I agree, I just wanted to confirm that with you so this PR will be merged when it is ready (for this release or the next one) to be merged.
Feel free to unhold :D

**Pull request merged**
