### PR TITLE
Refactor getMachine to clarify machine-not-found error conditions

### PR DESCRIPTION
**Pull request by clobrano**
Clarified the conditions under which an error would be returned or not
when the Machine was not found in the cluster.

### CODE REVIEW

**Comment by clobrano** [comment]
Regarding [this](https://github.com/medik8s/machine-deletion-remediation/pull/111#discussion_r1438838676) comment

> I do think this is still a bit confusing because isUnhandledMachine value may not reflect the actual logic.
> IIUC We only decide that the machine is unhandled after we also check ownerRef & remediation.
> So to put it in other words isUnhandledMachine value may equal true when logically it is actually need to be false.

I think that we can consider a Machine "unhandled" even before checking `ownerRef` and remediation, as unhandled does not necessarily mean we can remediate it, so I went for renaming the `mustExist` variable in `isUnhandledMachine`

**Comment by slintes** [comment]
/lgtm

giving others the chance to review as well
/hold

**Pull request merged**
