### PR TITLE
Bump go version to 1.20

### PR DESCRIPTION
**Pull request by clobrano**
Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>

### CODE REVIEW

**Comment by slintes** [comment]
Friendly reminder, this is the Go version used in CI:
https://github.com/medik8s/machine-deletion-remediation/blob/main/.ci-operator.yaml#L4

**Review by slintes — APPROVED** [review]
don´t forget to update ds config 🙂

**Comment by clobrano** [comment]
> don´t forget to update ds config :slightly_smiling_face:

sorry, what does 'ds' stand for? downstream? :sweat_smile:

**Comment by mshitrit** [comment]
/lgtm

> Friendly reminder, this is the Go version used in CI: https://github.com/medik8s/machine-deletion-remediation/blob/main/.ci-operator.yaml#L4

Good point.
Also (for future PRs) in case you want to save the trouble of updating the go version in both repos you can have the CI pull the go version from MDR repo.
- [Here](https://github.com/medik8s/self-node-remediation/pull/129) is an example from SNR of how to expose it to CI
- [Here](https://github.com/openshift/release/pull/40372) is an example of how to let CI repo to use that version.

>sorry, what does 'ds' stand for? downstream? sweat_smile

I'm fairly sure that was the intention, but looks [fine](https://gitlab.cee.redhat.com/dragonfly/machine-deletion-remediation/-/blob/rhwa-mdr-0.2-rhel-8/distgit/containers/machine-deletion-remediation-operator/Dockerfile.in#L2) IIUC

**Pull request merged**
