### PR TITLE
Add missing update of Conditions description in YAMLs

### PR DESCRIPTION
**Pull request by clobrano**
Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>

### CODE REVIEW

**Review by slintes — APPROVED** [review]
can be in a follow up, but what about adding a test for this? :) 

/hold

**Comment by clobrano** [comment]
We already have some, or did you mean a different thing?

- [e2e](https://github.com/medik8s/machine-deletion-remediation/blob/ca36076cf74931857831402c6135da86c2415af5/e2e/e2e_test.go#L94-L100)
- [package tests](https://github.com/medik8s/machine-deletion-remediation/blob/ca36076cf74931857831402c6135da86c2415af5/controllers/machinedeletionremediation_controller_test.go#L157-L189)

**Comment by slintes** [comment]
I mean a test for missing manifest updates.
Something along  `make generate manifests bundle verify-no-changes` (didn't check Makefile / test config on what's the best way to add this)

**Comment by clobrano** [comment]
> I mean a test for missing manifest updates. Something along `make generate manifests bundle verify-no-changes` (didn't check Makefile / test config on what's the best way to add this)

ah got it! Sure I'll add it in a follow up

**Pull request merged**
